import type { components } from './generated/schema'
export type Item = components['schemas']['Item']
export type Library = components['schemas']['Library']
export type ItemDetail = components['schemas']['ItemDetail']
export type ItemPage = components['schemas']['ItemPage']
export type ServerInfo = components['schemas']['ServerInfo']
export type Capabilities = components['schemas']['PlaybackCapabilities']
export type PlaybackDecision = components['schemas']['PlaybackDecision']
export type PlaybackState = components['schemas']['PlaybackState']
export type PlaybackSession = components['schemas']['PlaybackSession']
export type Knowledge = components['schemas']['Knowledge']
export type User = components['schemas']['User']
export type MediaSource = components['schemas']['MediaSource']
export type MediaPart = components['schemas']['MediaPart']

export type ContinueWatchingPage = components['schemas']['ContinueWatchingPage']
export type ContinueWatchingEntry = components['schemas']['ContinueWatchingEntry']
